
spring:
  datasource:
    password: gllue123
    url: jdbc:tracing:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
